name: dem_app
description: "DEM — Application de livraison à moto"
publish_to: 'none'
version: 1.1.0+7

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP
  dio: ^5.4.0

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.0

  # Stockage local (token JWT)
  shared_preferences: ^2.2.3

  # Guidage vocal navigation
  flutter_tts: ^4.2.0

  # Localisation + boussole
  geolocator: ^13.0.1
  flutter_compass: ^0.8.0

  # Carte
  google_maps_flutter: ^2.9.0
  google_maps_flutter_android: ^2.14.0
  google_maps_flutter_platform_interface: ^2.7.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Firebase
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.3.1
  firebase_messaging: ^15.1.5

  # WebSocket (temps réel — dispatch courses)
  socket_io_client: ^2.0.3+1

  # UI
  pin_code_fields: ^8.0.1          # Champ OTP
  country_code_picker: ^3.0.0      # Indicatif téléphone
  loading_animation_widget: ^1.2.1 # Loaders
  flutter_svg: ^2.0.10             # Logo SVG
  geocoding: ^4.0.0
  flutter_contacts: ^2.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2             # Photo de profil / documents
  url_launcher: ^6.3.1             # Support (tel, email, WhatsApp)
  flutter_local_notifications: ^21.0.0
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  # Adaptive icon Android 8+ (API 26+)
  # foreground : logo DEM transparent (512x512 RGBA)
  # background : couleur primaire DEM
  adaptive_icon_foreground: "assets/DEM.png"
  adaptive_icon_background: "#1AB8CC"

flutter:
  uses-material-design: true
  assets:
    - assets/DEM.png
    - assets/map_style_day.json
    - assets/map_style_waze.json
    - assets/icons/
    - assets/images/
