// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjfKsD6W5aj51PzVJt1ZleKSjlwne0mo',
    appId: '1:75751133767:web:931404283d2bb719cd1762',
    messagingSenderId: '75751133767',
    projectId: 'dem-app-ec8c4',
    authDomain: 'dem-app-ec8c4.firebaseapp.com',
    storageBucket: 'dem-app-ec8c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT-D__2AjJ-RlpNn3UhKmthKp80mzBJpg',
    appId: '1:75751133767:android:46a0977a5fc1815ccd1762',
    messagingSenderId: '75751133767',
    projectId: 'dem-app-ec8c4',
    storageBucket: 'dem-app-ec8c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURDrCI2IllVx-_x7U0yRIISVBj1tlNSs',
    appId: '1:75751133767:ios:87cfb13f317f2639cd1762',
    messagingSenderId: '75751133767',
    projectId: 'dem-app-ec8c4',
    storageBucket: 'dem-app-ec8c4.firebasestorage.app',
    iosBundleId: 'com.dem.demApp',
  );
}
